### PR TITLE
Moved API token expiration time into config (task #10034)

### PR DESCRIPTION
**Pull request by stepanov**

### CODE REVIEW

**Comment by mamchenkov** [comment]
@stepanov we also have it in other places .. I see it in `src/Controller/Api/V1/V0/UsersController.php`

**Comment by mamchenkov** [comment]
@stepanov there are some failing tests

**Comment by stepanov** [comment]
> @stepanov there are some failing tests

Yes, I know, cannot reproduce it locally.

**Comment by stepanov** [comment]
@mamchenkov @georgeconstantinou  The test failed because of error: 

`[Firebase\JWT\ExpiredException] Expired token`

Do you have idea why it happens?

**Comment by anvyst** [comment]
@stepanov It happened because of wrong constant call within `Configure::read()` call. There's no `Api` key, but there's `API`. Due to that `expireTime` was returning `null`, thus the JWT token didn't have expiration time. This unit test derives from `extenal` group, which can be run using `./vendor/bin/phpunit --group external` to test it on local

**Pull request merged**
